### ISSUE TITLE
文面の作成

### ISSUE THREAD

**Issue by KikyoNanakusa** [GreenTeaProgrammers/greenteaProgrammersPortfolio#3]
- [x] Aboutの文章の作成

- [x] Worksの文章の作成

- [x] Membersの文章の作成

**Comment by Hosi121** [comment]
文章、次の感じでどうでしょうか

## about

静岡大学の学生グループで、主にハッカソンに出場しています。意欲的なメンバーで構成され、日々、開発や自己研鑽に取り組んでスキルアップに努めています。チームとして、競技プログラミングやCTF、アプリ開発やウェブ開発など幅広いドメインに精通しています。

受賞歴
Open Hack U 2024 TOKYO…優秀賞

## works

-  ほいくる～ず （横にアイコン）

昨今、保育園の通園バスに関する問題が叫ばれています。
「ほいくるーず」はそんな諸問題を立ち向かいます。園児たちの顔認証や時間予測、忘れ物の音声通知など、子供たちに寄り添いながらITの力で解決しました。
本作品は、LineYahooが主催するOpen Hack U 2024 TOKYOにて優秀賞を受賞しました。 

アプリイメージ
（写真）

システム構成図
（写真）

-  タスクエスト（横にアイコン）

やらなきゃいけないメンドウなこと。私たちはそれに日々頭を悩ませています。
私たちはタスクを行う過程に注目し、タスクを行う中で、「楽しい」を実現するには何が必要なのかを考えました。
タスクをやっつける。そんなコンセプトをもとに新しいタスク管理ゲームを作成しました。

アプリイメージ
（写真）

システム構成図
（写真）

## Member

これは個々人に一言書いてもらうでいいんじゃないでしょうか？
年齢/性別までは載せてもいい気がしますが、コンセンサス取りましょう
技術スタックは[スキルアイコン](https://skillicons.dev/)を使用してかっこよくしたいです（願望）

**Comment by KikyoNanakusa** [comment]
![image](https://github.com/GreenTeaProgrammers/greenteaProgrammersPortfolio/assets/65284574/54fb6ae8-a6b5-4b7f-8896-ce6330b0ba95)
![image](https://github.com/GreenTeaProgrammers/greenteaProgrammersPortfolio/assets/65284574/8ac1dfa5-ec55-40a5-b0f3-b00a55547dcb)

**Comment by Hosi121** [comment]
![image](https://github.com/GreenTeaProgrammers/greenteaProgrammersPortfolio/assets/128687243/4465c8cc-00a9-4da9-a3e1-85547593a2ed)
![image](https://github.com/GreenTeaProgrammers/greenteaProgrammersPortfolio/assets/128687243/2a73ba03-db9e-44bb-83b9-78179b2edd61)

**Comment by KikyoNanakusa** [comment]
<img width="249" alt="スクリーンショット 2023-09-14 165005" src="https://github.com/GreenTeaProgrammers/greenteaProgrammersPortfolio/assets/65284574/0b0a1581-30a9-4913-b5fb-2ac2eff2a296">

**Comment by Hosi121** [comment]
# 本文仮案

##  メンバー紹介

### Name（の横にgithubとTwitter）
B1~4
担当(役割,領域)：(ex:designとかbackendとかfrontendとか？みんな複数択あるから悩みどころ)
技術スタック：（スキルアイコン）
一言：ここは任意

Twitterは載せてもいいか許可とる＆一言募集する

このぐらい簡素でいいと思います
